version: '3'

services:
  squid:
    image: sameersbn/squid:3.3.8-23
    restart: always
    ports:
      - 3128:3128
    volumes:
      - /var/services/squid/data/conf/squid.conf:/etc/squid3/squid.conf
      - /var/services/squid/data/cache:/var/spool/squid3
      - /var/services/squid/data/logs:/var/log/squid3/
